### ISSUE TITLE
Knowledge SDG jobs are broken

### ISSUE THREAD

**Issue by nerdalert** [instructlab/instructlab-bot#249]
BAM is looking into it. Track details in https://redhat-external.slack.com/archives/C06RTCN0PMF/p1713378110021089?thread_ts=1713368339.682139&cid=C06RTCN0PMF

No actions atm from us. Looks like the BAM side might need to pull latest? ¯\_(ツ)_/¯

**Comment by vishnoianil** [comment]
@nerdalert I think this issue is resolved now? If not please re-open the issue.
