### ISSUE TITLE
precheck: Invalid Content-Type header in response

### ISSUE THREAD

**Issue by bjhargrave** [instructlab/instructlab-bot#291]
The result of precheck is a page with .log and .yaml files. 

However, the server response has 

> Content-Type: application/json-lines+json

for both files. The .log file is text and the .yaml file is YAML. 

The incorrect content type in the response causes the browser to report an error that the file is not valid JSON.

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by nerdalert** [comment]
@bjhargrave that's my fault 👋 Introduced it with the formatting. Was trying to leave this file handling method generic. https://github.com/instructlab/instructlab-bot/blob/1a8b79e3f877c4d9030657d1d1bbbcbedbda0eea/worker/cmd/generate.go#L1052
