### ISSUE TITLE
Context in Precheck broken

### ISSUE THREAD

**Issue by mingxzhao** [instructlab/instructlab-bot#306]
Tracking issue of broken context in precheck command. Worked on in #267 but issue seems to still exist. 

As seen [here](https://github.com/instructlab/taxonomy/pull/738) the bot seems to be passing context that is completely ignored by the model or does not complete the passing of context.

**Comment by ckadner** [comment]
Going off of this example:

```


/usr/local/bin/ilab chat --quick-question can you solve the following riddle? Two turkeys in front of the turkey, two turkeys behind the turkey, tell me how many total turkeys? --tls-insecure --endpoint-url https://merlinite-7b-vllm-openai.apps.fmaas-backend.fmaas.res.ibm.com/v1 --context Form W-2 --model /shared_model_storage/transformers_cache/models--ibm--merlinite-7b/snapshots/233d12759d5bb9344231dafdb51310ec19d79c0e
INFO 2024-04-29 19:20:49,315 chat.py:474 Context Form not found in the config file. Using default.
INFO 2024-04-29 19:20:49,346 _client.py:1026 HTTP Request: POST https://merlinite-7b-vllm-openai.apps.fmaas-backend.fmaas.res.ibm.com/v1/chat/completions "HTTP/1.1 200 OK"
Thank you for the riddle! You've presented an interesting conundrum. I'd be happy to help you solve it.

The riddle states that there are two turkeys in front of the turkey and two turkeys behind the turkey. Let's break down the information given:

1. Two turkeys are in front of the turkey, which means there is one turkey in the middle.
2. Two turkeys are behind the turkey, which means there is also one turkey in the middle.

To find the total number of turkeys, we can add the number of turkeys in front and behind the turkey in the middle:

- Turkeys in front: 2 (one turkey in the middle)
- Turkeys behind: 2 (one turkey in the middle)

Adding these together, we get:

- Total turkeys: 2 (front) + 2 (behind) + 1 (middle) = 5 turkeys

However, the riddle states that the answer is W-2, which doesn't correspond to the total number of turkeys we calculated. It seems there might be a mistake in the riddle or an additional piece of information missing.

If you have any further clarification or additional information about the riddle, I'd be happy to reevaluate the answer. In its current form, the answer is 5 turkeys, but the riddle seems to indicate a different answer.
```

And this code snippet:
https://github.com/instructlab/instructlab/blob/4c1f09a911984f1066e3e926722511a61bfbc1ac/src/instructlab/lab.py#L550-L556

```Python
@click.option(
    "-c",
    "--context",
    default="default",
    show_default=True,
    help="Name of system context in config file.",
)
```

The warning indicates a different kind of "context" required here

**Comment by vishnoianil** [comment]
Digging into chat.py, it looks like there are only two context available 

```
CONTEXTS = {
    "default": get_sysprompt(),
    "cli_helper": "You are an expert for command line interface and know all common commands. Answer the command to execute as it without any explanation.",
}
```

and looks like this context is not really the context that we are referring to in qna.yaml. 

Also i think the command we are using is also not correct, as per the code in the instructlab main branch. `quick-question` is just a flag, it doesn't take any input as such. If this flag is set, ilab chat will exit once the question asked through `--question`  is answered. I think ilab chat expect that the question should be passed with `--question` flag and with `--quick-question` flag if you want prompt to exit.

https://github.com/instructlab/instructlab/blob/main/src/instructlab/lab.py#L567
```@click.option(
    "-qq",
    "--quick-question",
    is_flag=True,
    help="Exit after answering question.",
)
``` 

@xukai92 @hickeyma @oindrillac @aakankshaduggal can you help us file the exact command that we should use with --endpoint-url for precheck/generate that takes the context as well?

**Comment by nerdalert** [comment]
Example from @mingxzhao with a precheck not showing any context showing that context doesn't appear to be getting passed:
https://github.com/instructlab/taxonomy/pull/756
